pipeline {
    agent any
    environment {
        CI = 'true'
    }
    stages {
        stage('Build') {
            steps {
                bat 'git fetch'
                bat 'git checkout auto-build'
                bat 'git reset --hard origin auto-build'
                bat 'npm install'
            }
        }
        stage('Deliver') {
            steps {
                bat './scripts/deliver.sh'
                input message: 'Finished using the web site? (Click "Proceed" to continue)'
                bat './scripts/kill.sh'
            }
        }
    }
}