export default {
  'device_addAuto.dialog.hasPasswordTip': '设备已存在密码，请输入密码',
  'device_addAuto.dialog.labels.group': '分组',
  'device_addAuto.dialog.labels.name': '名称',
  'device_addAuto.dialog.requireAgain': '请再次输入密码',
  'device_addAuto.dialog.requiredPassword': '请输入密码',
  'device_addAuto.dialog.setPassword': '设置设备密码',
  'device_addAuto.dialog.title': '自动添加',
  'device_addAuto.dialog.userAdminPassword': '使用Admin密码',
  'device_addAuto.hasAccess': '已接入',
  'device_addAuto.message.addSuccess': '添加成功',
  'device_addAuto.message.nameLeg': '设备名称仅限255个字符',
  'device_addAuto.message.requiredAgain': '请输入确认密码',
  'device_addAuto.message.requiredName': '请输入设备名称',
  'device_addAuto.message.requiredPassword': '请输入密码',
  'device_addAuto.search.reSearch': '重新检查',
  'device_addAuto.search.res': '搜索到设备',
  'device_addAuto.search.searching': '正在搜索中',
  'device_addAuto.tableHeader.deviceGroup': '设备组',
  'device_addAuto.tableHeader.deviceKey': '设备序列号',
  'device_addAuto.tableHeader.deviceName': '设备名称',
  'device_addAuto.tableHeader.handle': '操作',
  'device_addAuto.tableHeader.ipAddress': 'IP地址',
  'device_addAuto.tableHeader.version': '软件版本',
  'device_addAuto.title': '自动添加',
  'device_addManual.add': '添加',
  'device_addManual.checkDevice': '检测到设备',
  'device_addManual.group': '分组',
  'device_addManual.hasPasswordTip': '设备已存在密码，请输入密码',
  'device_addManual.ipAddress': 'IP地址',
  'device_addManual.message.addSuccess': '添加成功',
  'device_addManual.message.nameLeg': '设备名称仅限255个字符',
  'device_addManual.message.noIp': '当前IP地址未检测到设备',
  'device_addManual.message.requiredAgain': '请输入确认密码',
  'device_addManual.message.requiredDevice': '请先检测设备',
  'device_addManual.message.requiredIpAddress': '请输入ip地址',
  'device_addManual.message.requiredName': '请输入设备名称',
  'device_addManual.message.requiredPassword': '请输入密码',
  'device_addManual.name': '名称',
  'device_addManual.passwordLabel': '设备密码',
  'device_addManual.samePassword': '重复密码',
  'device_addManual.setPassword': '设置设备密码',
  'device_addManual.setPasswordTip': '请设置密码',
  'device_addManual.title': '手动添加',
  'device_addManual.userAdminPassword': '使用Admin密码',
  'device_check.deviceDisabled': '设备禁用',
  'device_check.deviceOffLine': '设备离线',
  'device_check.dialog.sync': '同步',
  'device_check.dialog.syncClient': '同步成客户端名称',
  'device_check.dialog.syncDevice': '同步成设备端名称',
  'device_check.message.delete': '删除',
  'device_check.message.forceDelete': '强制删除',
  'device_check.message.forceDeleteTip':
    "强制删除设备，将删除系统保存的所有设备信'息，但保留设备内的所有数据",
  'device_check.message.hasDelete': '设备已删除',
  'device_check.message.hasEnable': '设备已启用',
  'device_check.message.requiredDevice': '请选择要升级的设备',
  'device_check.message.syncSuccess': '同步成功',
  'device_check.search.batchUpgrade': '批量升级',
  'device_check.search.checkRes': '搜索到设备',
  'device_check.search.checking': '正在检查中',
  'device_check.search.noDataTip': '没有设备或客户端需要升级',
  'device_check.search.reCheck': '重新检查',
  'device_check.search.tip1': '检查设备是否为最新版本',
  'device_check.search.tip2': '通过版本升级，提供更优质服务',
  'device_check.search.tip3': '搜索到设备',
  'device_check.table.enable': '启用',
  'device_check.table.forceDelete': '强制删除',
  'device_check.table.labels.ClientPlateName': '客户端名称',
  'device_check.table.labels.deviceKey': '设备序列号',
  'device_check.table.labels.devicePlateName': '设备端名称',
  'device_check.table.labels.handle': '操作',
  'device_check.table.labels.ipAddress': 'IP地址',
  'device_check.table.labels.version': '软件版本',
  'device_check.table.sync': '同步',
  'device_check.table.tabs.tab1': '版本一致',
  'device_check.table.tabs.tab2': '设备版本低',
  'device_check.table.tabs.tab3': '客户端版本低',
  'device_check.table.tabs.tab4': '离线设备',
  'device_check.table.tip': '请到客户端设置页面升级客户端版本',
  'device_check.table.upgrade': '升级',
  'device_check.title': '检查设备',
  'device_config.configError':
    '设备配置内容存在错误，请切换标签页核对后重新提交',
  'device_config.configSuccess': '设备配置成功！',
  'device_config.dialog.deviceKey': '设备序列号',
  'device_config.dialog.deviceName': '设备名称',
  'device_config.dialog.failReason': '失败原因',
  'device_config.dialog.title': '配置失败设备',
  'device_config.generalParams.delayTimeForCloseDoor': '继电器控制时间',
  'device_config.generalParams.delayTimeForCloseDoor_tip1':
    "继电器控制开门到关门之'间的时间间隔",
  'device_config.generalParams.delayTimeForCloseDoor_tip2':
    "请输入100-25500之间的'整数，向下取整百",
  'device_config.generalParams.identifyDistance': '识别距离',
  'device_config.generalParams.identifyDistanceTip':
    "例如识别距离在0.5米以内，设备'只会检测0.5米以内的人脸",
  'device_config.generalParams.miDistance': '%{num}米以内',
  'device_config.generalParams.miDistances': '%{num}米以内',
  'device_config.generalParams.noDistance': '无限制',
  'device_config.generalParams.recRank': '活体检测',
  'device_config.generalParams.recRankTip': '检测是真人还是照片',
  'device_config.generalParams.second': '秒',
  'device_config.generalParams.timeWindow': '时间窗',
  'device_config.generalParams.timeWindowTip':
    "在对应时间窗内，设备只会上传一次识别'记录",
  'device_config.generalParams.title': '通用参数',
  'device_config.identifyParams.comModType': '串口输出模式',
  'device_config.identifyParams.comModTypeCustom': '自定义',
  'device_config.identifyParams.comModTypeNoOutPut': '不输出',
  'device_config.identifyParams.comModTypeOpen': '开门',
  'device_config.identifyParams.comModTypeOutPutCard': '输出idcardNum',
  'device_config.identifyParams.comModTypeOutPutId': '输出人员id',
  'device_config.identifyParams.comModTypeOutPutPhone': '输出phone',
  'device_config.identifyParams.comModTypeTip1':
    "串口支持输出韦根信号，设备需要外接'串口→韦根信号转换小板，小板由本公司定制。自定义内容传入格式",
  'device_config.identifyParams.comModTypeTip2':
    "韦根26：#26WG{idcardNum}#，韦根'34：#34WG{idcardNum}#",
  'device_config.identifyParams.comModTypeTip3':
    "注意：{idcardNum}+数字组合后，韦'根26范围为1-65535，有效范围为5位；韦根34范围为1-4294967295，有效范围为10位。若超出'范围，则输出的信号会进行转换，输出无效信号。",
  'device_config.identifyParams.deviceRule3':
    "允许{name}、{tag}、数字、中英文和中英'文符号",
  'device_config.identifyParams.failParams': '识别失败参数',
  'device_config.identifyParams.identifyFail': '识别失败',
  'device_config.identifyParams.identifyFailCount': '识别失败判定次数',
  'device_config.identifyParams.identifyFailCountTip':
    "设备比对一定次数，均不通过，'则判定为识别失败。次数越大，精度越高，时间越长范围（1-20的整数）",
  'device_config.identifyParams.identifyFailTip':
    "控制设备是否提示识别失败,开启后将'保存陌生人的记录和现场抓拍照片",
  'device_config.identifyParams.isOpenRelay': '继电器输出',
  'device_config.identifyParams.isOpenRelayTip':
    "继电器输出打开，则识别后会输出开关'量信号",
  'device_config.identifyParams.modCustom': '自定义',
  'device_config.identifyParams.modExample': '如：注意陌生人！',
  'device_config.identifyParams.modFailContent': '识别失败后语音播报内容',
  'device_config.identifyParams.modFailContent2': '播报识别失败',
  'device_config.identifyParams.modName': '播报名字',
  'device_config.identifyParams.modNone': '不播报',
  'device_config.identifyParams.modRule': '只允许数字、英文和汉字',
  'device_config.identifyParams.modRule2': '只允许数字、中英文和中英文符号',
  'device_config.identifyParams.modRule3':
    '允许{name}、{tag}、数字、英文和汉字',
  'device_config.identifyParams.modRule4': '允许数字、英文和英文符号',
  'device_config.identifyParams.name': '姓名',
  'device_config.identifyParams.nameExample': '如：{name}权限不足',
  'device_config.identifyParams.nameRule3': '如：{name}权限不足！',
  'device_config.identifyParams.noAccess': '权限不足',
  'device_config.identifyParams.noAccessModTip': '权限不足时语音播报内容',
  'device_config.identifyParams.noAccessNameTip': '播报姓名权限不足',
  'device_config.identifyParams.noAccessParams': '权限不足参数',
  'device_config.identifyParams.noAccessParamsTip':
    "识别成功后提示权限不足，例如：'甲在08：00-20：00方可进入公司，然而他在21：00来到公司，则甲为权限不足",
  'device_config.identifyParams.onlyNumIdCard': '只允许{id}、{idcardNum}和数字',
  'device_config.identifyParams.onlyNumber': '只允许数字',
  'device_config.identifyParams.recSucWiegandType': '韦根输出模式',
  'device_config.identifyParams.recSucWiegandTypeNoOutput': '不输出',
  'device_config.identifyParams.recSucWiegandTypeTip':
    "{idcardNum}+数字组合后，韦'根26范围为1-65535，有效范围为5位；韦根34范围为1-4294967295，有效范围为10位。若超出'范围，则输出的信号会进行转换，输出无效信号",
  'device_config.identifyParams.recSucWiegandTypeWk': '韦根',
  'device_config.identifyParams.screen1': '屏幕显示文字1',
  'device_config.identifyParams.screen1ShowCustom': '自定义',
  'device_config.identifyParams.screen1ShowName': '显示名字',
  'device_config.identifyParams.screen1ShowNone': '不显示内容',
  'device_config.identifyParams.screen2': '屏幕显示文字2',
  'device_config.identifyParams.screen2Custom': '自定义',
  'device_config.identifyParams.screen2IdentifySuccess': '识别成功',
  'device_config.identifyParams.screenShowText': '屏幕显示文字',
  'device_config.identifyParams.showFail': '显示识别失败',
  'device_config.identifyParams.successParams': '识别成功参数',
  'device_config.identifyParams.thunkModeTip1':
    "串口支持输出韦根信号，设备需要外接串'口→韦根信号转换小板，小板由本公司定制。",
  'device_config.identifyParams.thunkModeTip2':
    "注意：韦根26范围为1-65535，有效范围'为5位；韦根34范围为1-4294967295，有效范围为10位。若超出范围，则输出的信号会进行转'换，输出无效信号。",
  'device_config.identifyParams.thunkModeTip3':
    "韦根26范围为1-65535，有效范围为5'位；韦根34范围为1-4294967295，有效范围为10位。若超出范围，则输出的信号会进行转换，输'出无效信号。",
  'device_config.identifyParams.thunkTip1':
    "串口支持输出韦根信号，设备需要外接串口→'韦根信号转换小板，小板由本公司定制。自定义内容传入格式：",
  'device_config.identifyParams.thunkTip2':
    "韦根26：#26WG{idcardNum}#，韦根34：'#34WG{idcardNum}#",
  'device_config.identifyParams.thunkTip3': '串口支持输出韦根信号',
  'device_config.identifyParams.thunkTip4':
    "允许{phone}、{idcardNum}、{id}、数字中'英文和中英文符号",
  'device_config.identifyParams.title': '识别参数',
  'device_config.identifyParams.ttsModType': '语音播报模式',
  'device_config.identifyParams.ttsModTypeExample': '如：{name}欢迎光临',
  'device_config.identifyParams.ttsModTypeTip': '识别成功后语音播报内容',
  'device_config.identifyParams.ttsModTypeTip2':
    "允许{name}、{tag}、数字、英文和汉'字",
  'device_config.identifyParams.ttsModTypeTip3':
    "允许{phone}、{idcardNum}、{id}、'数字、英文和英文符号",
  'device_config.identifyType.cardIdentify': '刷卡识别',
  'device_config.identifyType.cardIdentifyTip':
    "当前刷卡识别与人卡合一不可共存，因为'它们使用同一个串口输出",
  'device_config.identifyType.chunk': '串口',
  'device_config.identifyType.hardware1': 'IC读卡器',
  'device_config.identifyType.hardware2': '新中新',
  'device_config.identifyType.hardware3': '精伦',
  'device_config.identifyType.hardware4': '中控',
  'device_config.identifyType.hardware5': '华视',
  'device_config.identifyType.identifyScores': '人脸识别阈值',
  'device_config.identifyType.identifyScoresTip':
    "（请输入0~100的整数，分数越高，识'别准确率越高。为保证准确率，建议值50~100）",
  'device_config.identifyType.moreIdentify': '多人识别',
  'device_config.identifyType.moreIdentifyTip': '识别区域内出现的人脸均会检测',
  'device_config.identifyType.pearsonWithCard': '人证比对',
  'device_config.identifyType.pearsonWithCardTip':
    "人证比对、刷卡、人卡合一不可使用'相同的卡号传输接口",
  'device_config.identifyType.personCard': '人卡合一',
  'device_config.identifyType.personCardTip':
    "当前刷卡识别与人卡合一不可共存，因为它'们使用同一个串口输出",
  'device_config.identifyType.photoIdentify': '人脸识别',
  'device_config.identifyType.recModeCardHardware': '外接硬件类型',
  'device_config.identifyType.recModeCardIntf': '卡号传输接口',
  'device_config.identifyType.recModeCardIntfTip':
    "（接口类型切换后需要重启设备才能'生效）",
  'device_config.identifyType.singleIdentify': '单人识别',
  'device_config.identifyType.singleIdentifyTip': '识别区域只检测最大人脸',
  'device_config.identifyType.title': '识别模式',
  'device_config.message.rule1': '请输入语音播报自定义内容',
  'device_config.message.rule2': '请输入1-255位字符',
  'device_config.message.rule3': '允许{name}、{tag}、数字、英文和汉字',
  'device_config.message.rule4': '请输入屏幕显示文字',
  'device_config.message.rule5': '请输入1-255位字符',
  'device_config.message.rule6': '请输入韦根输出自定义内容',
  'device_config.message.rule7': '只允许数字',
  'device_config.message.rule8': '韦根26范围为1-65535',
  'device_config.message.rule9': '韦根34范围为1-4294967295',
  'device_config.message.rule10': '请输入人脸识别阈值',
  'device_config.message.rule11': '请输入1-100之间的整数',
  'device_config.message.rule12': '请输入串口输出自定义内容',
  'device_config.message.rule13': '允许数字、英文和英文符号',
  'device_config.message.rule14':
    "允许{phone}、{idcardNum}、{id}、数字、英文和英文'符号",
  'device_config.message.rule15': '请输入时间窗',
  'device_config.message.rule16': '请输入继电器控制时间',
  'device_config.message.rule17': '请输入100-25500之间的整数',
  'device_config.message.rule18': '请输入识别失败判定次数',
  'device_config.message.rule20': '请输入韦根输出自定义内容',
  'device_config.message.rule21': '韦根26范围为1-65535',
  'device_config.message.rule22': '韦根34范围为1-4294967295',
  'device_config.message.rule23': '请输入显示文字内容1',
  'device_config.message.rule24': '请输入显示文字内容2',
  'device_config.message.rule27': '文件格式不正确，请重新选择',
  'device_config.message.rule28': '文件过大，请重新选择',
  'device_config.message.rule29': '请输入1-20的整数',
  'device_config.message.rule30': '只允许{idcardNum}、{id}和数字',
  'device_config.message.rule31': '请输入0-2147483647之间的整数',
  'device_config.showParams.arrowAcross': '横屏',
  'device_config.showParams.arrowColumn': '竖屏',
  'device_config.showParams.bigScreen': '大屏模式',
  'device_config.showParams.custom': '自定义',
  'device_config.showParams.customType': '自定义模式',
  'device_config.showParams.deviceGroup': '设备组',
  'device_config.showParams.deviceKey': '设备序列号',
  'device_config.showParams.deviceName': '设备名称',
  'device_config.showParams.disabledImg': '禁用界面图片',
  'device_config.showParams.hidden': '不显示',
  'device_config.showParams.imgStandard1': '照片比例1:1，大小不得超过2M',
  'device_config.showParams.imgStandard2': '文件格式支持jpg、jpeg、png',
  'device_config.showParams.imgStandard3': '如：公司logo',
  'device_config.showParams.imgStandard4': '如：二维码',
  'device_config.showParams.imgStandard5': '用于设备禁用时的展示',
  'device_config.showParams.intro': '简介',
  'device_config.showParams.normalType': '传统模式',
  'device_config.showParams.personCount': '人数',
  'device_config.showParams.previewDefaultImg': '查看默认图',
  'device_config.showParams.scrDisplayText1Content': '如：公司名称',
  'device_config.showParams.scrDisplayText2Content': '如：东门口设备',
  'device_config.showParams.screenArrow': '屏幕方向',
  'device_config.showParams.showConfig': '显示设置',
  'device_config.showParams.showForBig': '用于大屏展示',
  'device_config.showParams.showImg': '显示图片',
  'device_config.showParams.showText': '显示文字',
  'device_config.showParams.slogan': '标语',
  'device_config.showParams.title': '显示参数',
  'device_config.title': '设备配置',
  'device_time.dialog.deviceKey': '设备序列号',
  'device_time.dialog.deviceName': '设备名称',
  'device_time.dialog.failReason': '失败原因',
  'device_time.dialog.title': '校时失败设备',
  'device_time.form.beijing': '北京',
  'device_time.form.message': '请填写完整时间',
  'device_time.form.selfTime': '本机时间',
  'device_time.form.setManual': '手动校时',
  'device_time.form.timeArea': '时区',
  'device_time.form.tip1':
    '提示：设置成功后，若设备未连入公网，则此时间会生效；',
  'device_time.form.tip2': '若设备连入公网，则会重新使用公网时间',
  'device_time.form.typeLabel': '校时方式',
  'device_time.successMsg': '设备校时成功！',
  'device_time.title': '设备校时',
  'device_upgrade.dialog.deviceKey': '设备序列号',
  'device_upgrade.dialog.deviceName': '设备名称',
  'device_upgrade.dialog.failReason': '失败原因',
  'device_upgrade.dialog.title': '升级失败设备',
  'device_upgrade.message.fileNoSupport': '文件格式不支持',
  'device_upgrade.message.packageError': '升级包包名错误,无法升级',
  'device_upgrade.message.requiredFirmware': '还未上传固件',
  'device_upgrade.message.upgradeSuccess': '固件升级成功！',
  'device_upgrade.select': '选择',
  'device_upgrade.title': '固件升级',
  'device_upgrade.upgrade': '升级',
  'device_upgrade.uploadLabel': '上传固件：',
  'device_wifi.dialogFail.deviceKey': '设备序列号',
  'device_wifi.dialogFail.deviceName': '设备名称',
  'device_wifi.dialogFail.failReason': '失败原因',
  'device_wifi.dialogFail.title': '网络配置失败设备',
  'device_wifi.dialogWire.IpType': 'IP类型',
  'device_wifi.dialogWire.fixIp': '固定IP',
  'device_wifi.dialogWire.fixSet': '固定设置',
  'device_wifi.dialogWire.gateway': '网关',
  'device_wifi.dialogWire.getIpAuto': '自动获取IP',
  'device_wifi.dialogWire.tip': '配置保存成功后，设备连上网线即生效',
  'device_wifi.dialogWire.title': '有线配置',
  'device_wifi.dialogWire.website': 'IP地址',
  'device_wifi.form.btnConnect': '连接',
  'device_wifi.form.btnWiredSet': '有线配置',
  'device_wifi.form.fixSet': '固定设置',
  'device_wifi.form.gateway': '网关',
  'device_wifi.form.getIpAuto': '自动获取IP',
  'device_wifi.form.ipType.label': 'IP类型',
  'device_wifi.form.ipType.value': '固定IP',
  'device_wifi.form.name': 'Wi-Fi名称',
  'device_wifi.form.password': 'Wi-Fi密码',
  'device_wifi.form.website': 'IP地址',
  'device_wifi.message.requiredDNS': '请输入DNS',
  'device_wifi.message.requiredGateway': '请输入网关',
  'device_wifi.message.requiredIp': '请输入IP地址',
  'device_wifi.message.requiredName': '请输入WI-FI名称',
  'device_wifi.message.requiredPassword': '请输入WI-FI密码',
  'device_wifi.saveSuccessMsg': '设备网络保存成功！',
  'device_wifi.setSuccessMsg': '设备网络配置成功！',
  'device_wifi.title': '网络配置',
  'group_add.addTitle': '添加设备组',
  'group_add.all': '全部',
  'group_add.editTitle': '编辑设备组',
  'group_add.form.device': '设备',
  'group_add.form.disabled': '禁用',
  'group_add.form.name': '名称',
  'group_add.form.offLine': '离线',
  'group_add.form.remark': '备注',
  'group_add.form.search': '搜索',
  'group_add.message.addSuccess': '添加成功',
  'group_add.message.requiredName': '请输入名称',
  'group_add.message.updateSuccess': '修改成功',
  'group_add.outGroup': '未分组',
  // 手动添加设备 key 值新增
  device_add_manual_confirm_self_message: '无法在自证机设备列表添加门禁设备',
  device_add_manual_confirm_self_message2: '是否把该设备添加到门禁设备列表？',
  device_add_manual_confirm_device_message: '无法在门禁设备列表添加自证机设备',
  device_add_manual_confirm_device_message2:
    '是否把该设备添加到自证机设备列表？',
  device_add_manual_confirm_button_text: '是',
  device_add_manual_confirm_cancel_button_text: '否',

  device_info_device_ip_type: 'IP类型',
  device_info_device_ip_type_1: 'DHCP',
  device_info_device_ip_type_2: '固定IP',
  device_info_device_has_password: '密码',
  device_info_device_has_password_no: '无',
  device_info_device_has_password_exist: '有',
  device_info_device_model: '设备型号',
  device_info_device_not_support: '暂不支持获取',
  device_info_device_type1: '客行一体机',
  device_info_device_type2: 'Link',
  device_info_device_type3: '5C',
  device_info_device_type4: 'DV300 平板',
  device_info_device_type5: 'DV300 模组',
  device_info_device_type6: 'CV500 模组',
  device_info_device_type7: '5K',
  // 1.2期增加文字
  ip_input_copy_error: '格式不正确',
  device_batch_operate_restore_text: '恢复默认配置',
  device_batch_operate_restore_fail: '恢复默认配置失败设备',
  device_batch_operate_restore_comfirm_title: '恢复默认配置',
  device_batch_operate_restore_comfirm_centent:
    '恢复后，设备配置将重置为默认值',
  device_batch_operate_restore_comfirm_submit: '恢复',
  device_batch_operate_restore_comfirm_success: '设备恢复默认配置成功',
  device_config_tabs_tip: '请勾选需要配置的参数',
  device_config_form_recModeCardPhoto: '现场照',
  device_config_form_whitelist: '身份证校验',
  device_config_form_whitelist_tip:
    '读取身份证信息后是否需要与数据库内人员的身份证号进行比对',
  device_upgrade_history_table_title: '历史上传列表',
  device_upgrade_history_table_name: '名称',
  device_upgrade_history_table_time: '时间',
  device_upgrade_history_table_operate: '操作',
  device_upgrade_history_table_operate_upgrade: '升级',
  device_upgrade_history_table_operate_delete: '删除',
  device_upgrade_history_table_operate_delete_comfirm_title: '删除',
  device_upgrade_history_table_operate_delete_comfirm_content:
    '删除后将不可恢复',
  device_upgrade_history_table_operate_delete_comfirm_submit: '删除',
  device_upgrade_history_table_operate_delete_comfirm_success: '删除成功',
  device_upgrade_leave_confirm_title: '离开',
  device_upgrade_leave_confirm_content: '离开此页面，将取消上传',
  device_upgrade_leave_confirm_submit: '离开',
  device_wifi_ip_conflict: 'IP地址已被占用，请重新设置',
  device_add_form_lang: '设置设备语言',
  device_batch_operate_lang_comfirm_title: '设置设备语言',
  device_batch_operate_lang_text: '设置设备语言',
  device_batch_operate_lang_fail: '设置语言失败设备',
  device_batch_operate_lang_success: '设备设置语言成功',
  device_batch_operate_lang_comfirm_form_lang_label: '语言',
  device_batch_operate_lang_comfirm_form_submit: '保存',
  device_batch_operate_empty_comfirm_title: '清空人员',
  device_batch_operate_empty_comfirm_content:
    '清空后，设备上人员信息将为空，客户端上将销权已有的设备-人员信息',
  device_batch_operate_empty_text: '清空人员',
  device_batch_operate_empty_fail: '清空人员失败设备',
  device_batch_operate_empty_success: '设备清空人员成功',
  device_batch_operate_empty_comfirm_form_submit: '清空',
  device_config_check_ip_text: 'IP地址校验中...',
  // 体温检测
  device_batch_temperature_comfirm_title: '设置体温检测',
  device_batch_operate_temperature_form_temp_check: '体温检测',
  device_batch_operate_temperature_form_temp_invalid: '体温异常',
  device_batch_operate_temperature_form_temp_invalid_voice: '体温异常语音播报',
  device_batch_operate_temperature_form_temp_voice_type1: '播报体温异常及温度',
  device_batch_operate_temperature_form_temp_voice_type2: '不播报',
  device_batch_operate_temperature_form_temp_voice_type3: '自定义',
  device_batch_operate_temperature_form_custom_voice_placeholder:
    '允许{temperature}、数字、英文和汉字',
  device_batch_operate_temperature_form_custom_voice_example:
    '如：{temperature}体温异常',
  device_batch_operate_temperature_form_custom_voice_validator1:
    '请输入自定义语音播报',
  device_batch_operate_temperature_text: '设置体温检测',
  device_batch_operate_temperature_fail: '设置体温检测失败设备',
  device_batch_operate_temperature_success: '设置体温检测成功',
  device_identify_person_temperature_number: '体温',
  device_identify_person_temperature_state: '体温状态',

  device_batch_operate_device_style1: '闸机平板',
  device_batch_operate_device_style2: '立式一体机',
  device_batch_operate_device_style3: '简洁模式',
  device_batch_operate_device_style: '其他',
  device_batch_operate_device_style_label: '设备模式',
  device_batch_operate_device_style_tip:
    '设备模式不同，设备屏幕上提示的测温区域不同',
  device_batch_operate_device_style_placeholder: '请输入设备模式其他类型',

  device_batch_operate_read_temperature_type_label: '测温模块类型',
  device_batch_operate_read_temperature_type_tip:
    '需要核对设备与测温模块类型是否匹配',
  device_batch_operate_read_temperature_type_placeholcer: '请输入测温模块类型',
  device_batch_operate_over_lab_value_label: '测温区域重叠率',
  device_batch_operate_over_lab_value_tip:
    '数值越大，人脸与屏幕上的测温区域的匹配度要求越高；此参数对设备模式-闸机平板不生效',
  device_batch_operate_over_lab_value_placeholder: '请输入测温区域重叠率',
  // 2020-03-12
  device_batch_operate_temperature_position: '测温位置',
  device_batch_operate_temperature_position_label1: '额头',
  device_batch_operate_temperature_position_label2: '手腕',
  device_batch_operate_temperature_position_tip:
    '测温位置不同，设备的提示音、提示画面不同',
  device_batch_operate_temperature_pass: '体温异常时通行',
  device_batch_operate_temperature_pass_label1: '不允许',
  device_batch_operate_temperature_pass_label2: '允许',

  device_batch_operate_temperature_measure_range: '有效温度范围',
  device_batch_operate_temperature_measure_range_tip:
    '若测温结果不在此范围内，则设备会提示请重新测量体温',
  device_batch_operate_temperature_measure_range_label1: '有效温度最低值',
  device_batch_operate_temperature_measure_range_label2: '有效温度最高值',
  device_batch_operate_temperature_measure_validator:
    '只允许{min}-{max}范围内小数点1位的数值',
  device_batch_operate_temperature_measure_placeholder1: '请输入有效温度最低值',
  device_batch_operate_temperature_measure_placeholder2: '请输入有效温度最高值',
  // 新增修改 key 值
  device_batch_operate_temperature_env_effect1: '低温补偿',
  device_batch_operate_temperature_env_effect1_tip:
    '开启后，当测量温度受环境影响低于人体正常体温后，将自动补偿为人体正常体温',
  device_batch_operate_temperature_env_effect_label1: '温度映射源',
  device_batch_operate_temperature_env_effect_label2: '温度映射目标',

  device_batch_operate_temperature_env_effect2: '高温补偿',
  device_batch_operate_temperature_env_effect2_tip:
    '开启后，检测到处于下方映射源的范围内的温度值将会被调整成映射目标范围',
  device_batch_operate_temperature_env_effect_validator5:
    '最高值必需大于最低值',
  device_batch_operate_temperature_env_effect_validator6:
    '低温补偿的温度映射源范围要小于高温补偿的温度映射源范围',
  device_batch_operate_temperature_env_effect_validator7: '请输入温度最低值',
  device_batch_operate_temperature_env_effect_validator8: '请输入温度最高值',

  device_batch_operate_temperature_more_btn1: '收起更多',
  device_batch_operate_temperature_more_btn2: '展开更多',
  device_batch_operate_temperature_unit: '体温单位',
  device_batch_operate_temperature_unit_type1: '摄氏度℃',
  device_batch_operate_temperature_unit_type2: '华氏度℉',
  // 设置口罩检测
  device_batch_mask_check_comfirm_title: '设置口罩检测',
  device_batch_operate_mask_check_form_temp_check: '口罩检测',
  device_batch_operate_mask_check_form_temp_invalid_voice:
    '未佩戴口罩语音播报模式',
  device_batch_operate_mask_check_form_temp_voice_type1: '播报未佩戴口罩',
  device_batch_operate_mask_check_form_temp_voice_type2: '不播报',
  device_batch_operate_mask_check_form_temp_voice_type3: '自定义',
  device_batch_operate_mask_check_form_custom_voice_placeholder:
    '允许数字、英文和汉字',
  device_batch_operate_mask_check_form_custom_voice_example:
    '如：未佩戴口罩不得进入',
  device_batch_operate_mask_check_form_custom_voice_validator1:
    '请输入未佩戴口罩语音播报自定义内容',
  device_batch_operate_mask_check_text: '设置口罩检测',
  device_batch_operate_mask_check_fail: '设置口罩检测失败设备',
  device_batch_operate_mask_check_success: '设备设置口罩检测成功',
  // 远程开门
  device_batch_operate_remote_opendoor_text: '远程开门',
  device_batch_operate_remote_opendoor_fail: '远程开门失败设备',
  device_batch_operate_remote_opendoor_success: '设备远程开门成功',

  // 设备配置方案
  device_batch_operate_device_config: '配置方案',
  device_batch_operate_device_config_add: '添加配置',
  device_batch_operate_device_config_update_time: '方案最近更新时间',
  device_batch_operate_device_config_default_name: '默认方案一'
}
