export default {
  // 设备校时
  device_time: {
    title: 'Device timing',
    form: {
      timeArea: 'Time zone',
      beijing: 'Beijing',
      typeLabel: 'Timing method',
      setManual: 'Manual timing',
      selfTime: 'Local time',
      tip1: 'Tips: The time will take effect after being set successfully if the device does not connect to the Internet;',
      tip2: 'The device will use the Internet time if it connects to the Internet',
      message: 'Please fill in the full time'
    },
    dialog: {
      title: 'Timing failure',
      deviceName: 'Device name',
      deviceKey: 'Device serial number',
      failReason: 'Failure reasons'
    },
    successMsg: 'Device timing success!'
  },
  // 网络配置: '  // Network configuration',
  device_wifi: {
    title: 'Network configuration',
    form: {
      name: 'Wi-Fi name',
      password: 'Wi-Fi password',
      ipType: {
        label: 'IP type',
        value: 'Fixed IP'
      },
      getIpAuto: 'Obtain IP automatically',
      fixSet: 'Fixed settings',
      website: 'IP address',
      gateway: 'Gateway',
      btnConnect: 'Connect',
      btnWiredSet: 'Wired configuration'
    },
    dialogWire: {
      title: 'Wired configuration',
      IpType: 'IP type',
      fixIp: 'Fixed IP',
      getIpAuto: 'Obtain IP automatically',
      fixSet: 'Fixed settings',
      website: 'IP address',
      gateway: 'Gateway',
      tip: 'Configuration will take immediate effect after saved successfully as device connects the network cable'
    },
    dialogFail: {
      title: 'Network configuration failed',
      deviceName: 'Device name',
      deviceKey: 'Device serial number',
      failReason: 'Failure reasons'
    },
    message: {
      requiredName: 'Please input Wi-Fi name',
      requiredPassword: 'Please input Wi-Fi password',
      requiredIp: 'Please input the IP address',
      requiredDNS: 'Please input the DNS',
      requiredGateway: 'Please input the gateway'
    },
    setSuccessMsg: 'Device network configured successfully!',
    saveSuccessMsg: 'Device network saved successfully!'
  },
  // 固件升级: '  // Firmware upgrade',
  device_upgrade: {
    title: 'Firmware upgrade',
    uploadLabel: 'Upload firmware:',
    select: 'Select',
    upgrade: 'Upgrade',
    dialog: {
      title: 'Failed to upgrade device',
      deviceName: 'Device name',
      deviceKey: 'Device serial number',
      failReason: 'Failure reasons'
    },
    message: {
      requiredFirmware: 'Firmware not uploaded yet',
      upgradeSuccess: 'Firmware upgraded successfully!',
      fileNoSupport: 'File format not supported',
      packageError: 'Upgrade package name error, failed to upgrade'
    }
  },
  // 设备配置: '  // Device configuration',
  device_config: {
    title: 'Device configuration',
    generalParams: {
      title: 'General parameters',
      timeWindow: 'Time window',
      timeWindowTip: "In the time window, only the first record of person's recognition records would be uploaded",
      second: 'second',
      recRank: 'Living body detection',
      recRankTip: 'Detect whether it is a real person or a photo',
      identifyDistance: 'Recognition distance',
      identifyDistanceTip: 'For example, if the recognition distance is within 0.5 meter, the device will only detect faces within 0.5 meter range',
      miDistance: 'Within %{num} meter',
      miDistances: 'Within %{num} meters',
      noDistance: 'No limit',
      delayTimeForCloseDoor: 'Relay control time',
      delayTimeForCloseDoor_tip1: 'Relay controls the time interval between door opening and closing',
      delayTimeForCloseDoor_tip2: 'Please input integers between 100-25500, round down with hundreds'
    },
    identifyParams: {
      title: 'Recognition parameters',
      successParams: 'Parameter of recognition success',
      ttsModType: 'Voice broadcast mode',
      ttsModTypeTip: 'Voice broadcast the content after successful recognition',
      ttsModTypeTip2: 'Allow {name}, {tag}, numbers, English and Chinese characters',
      ttsModTypeTip3: 'Allow {phone}, {idcardNum}, {id}, numbers, English and English symbols',
      ttsModTypeExample: 'For example: {name} welcome',
      modName: 'Broadcast name',
      modNone: 'Not broadcast',
      modCustom: 'Custom',
      screen1: 'Screen display text 1',
      screen1ShowName: 'Display name',
      screen1ShowNone: 'Not display content',
      screen1ShowCustom: 'Custom',
      screen2: 'Screen display text 2',
      screen2IdentifySuccess: 'Recognition success',
      screen2Custom: 'Custom',
      comModType: 'Serial port output mode',
      comModTypeTip1: 'Serial port supports outputting Wiegand signal, device needs external serial port → Wiegand signal conversion plate, which is customized by our company. Custom passing format of content',
      comModTypeTip2: 'Wiegand 26: #26WG{idcardNum}#, Wiegand 34: #34WG{idcardNum}#',
      comModTypeTip3: 'Attention: {idcardNum} + combination of numbers, the range of Wiegand 26 is 1-65535, effective range is 5-digit; the range of Wiegand 34 is 1-4294967295, effective range is 10-digit. If exceeds the range, output signal will be converted and output ineffective signal.',
      comModTypeOpen: 'Open the door',
      comModTypeNoOutPut: 'Not output',
      comModTypeOutPutId: 'Output person ID',
      comModTypeOutPutCard: 'Output idcardNum',
      comModTypeOutPutPhone: 'Output phone',
      comModTypeCustom: 'Custom',
      recSucWiegandType: 'Wiegand output mode',
      recSucWiegandTypeTip: '{idcardNum} + combination of numbers, the range of Wiegand 26 is 1-65535, effective range is 5-digit; the range of Wiegand 34 is 1-4294967295, effective range is 10-digit. If exceeds the range, output signal will be converted and output ineffective signal',
      recSucWiegandTypeNoOutput: 'Not output',
      recSucWiegandTypeWk: 'Wiegand',
      onlyNumIdCard: 'Only allow {idcardNum}, {id} and numbers',
      onlyNumber: 'Allow numbers only',
      isOpenRelay: 'Relay output',
      isOpenRelayTip: 'Turn on Relay output, digital signal will be output after recognition',
      failParams: 'Parameter of recognition failure',
      identifyFail: 'Recognition failure',
      identifyFailTip: 'Control the device to remind recognition failure or not, stranger records and site capture photos will be saved after turned on',
      identifyFailCount: 'Number of times for judging recognition failure',
      identifyFailCountTip: 'Device will compare for a certain number of times, if not pass, then will judge as recognition failure. The more the number of times, the higher the accuracy, the longer the time; Range (integer between 1-20)',
      modFailContent: 'Voice broadcast content after recognition failure',
      modFailContent2: 'Broadcast recognition failure',
      modRule: 'Only numbers, English and Chinese characters allowed',
      modExample: 'For example: Stranger, attention please!',
      screenShowText: 'Screen display text',
      showFail: 'Display recognition failure',
      modRule2: 'Only numbers, Chinese and English and Chinese and English symbols allowed',
      modRule4: 'Allow numbers, English and English symbols',
      thunkModeTip1: 'Serial port supports outputting Wiegand signal, device needs external serial port → Wiegand signal conversion plate, which is customized by our company.',
      thunkModeTip2: 'Attention: the range of Wiegand 26 is 1-65535, effective range is 5-digit; the range of Wiegand 34 is 1-4294967295, effective range is 10-digit. If exceeds the range, output signal will be converted and output ineffective signal.',
      thunkModeTip3: 'The range of Wiegand 26 is 1-65535, effective range is 5-digit; the range of Wiegand 34 is 1-4294967295, effective range is 10-digit. If exceeds the range, output signal will be converted and output ineffective signal.',
      noAccessParams: 'Parameter of insufficient permission',
      noAccessParamsTip: 'Remind insufficient permission after successful recognition, for example: A can enter into the company between 08:00-20:00, if he comes to the company at 21:00, then A has insufficient permission',
      noAccessModTip: 'Voice broadcast the content when permission is insufficient',
      noAccessNameTip: 'Broadcast name and insufficient permission',
      modRule3: 'Allow {name}, {tag}, numbers, English and Chinese characters',
      nameExample: 'For example: {name} insufficient permission',
      name: 'Name',
      deviceRule3: 'Allow {name}, {tag}, numbers, Chinese and English and Chinese and English symbols',
      nameRule3: 'For example: {name} insufficient permission!',
      noAccess: 'Insufficient permission',
      thunkTip1: 'Serial port supports outputting Wiegand signal, device needs external serial port → Wiegand signal conversion plate, which is customized by our company. Custom content inputting format:',
      thunkTip2: 'Wiegand 26: #26WG{idcardNum}#, Wiegand 34: #34WG{idcardNum}#',
      thunkTip4: 'Allow {phone}, {idcardNum}, {id}, numbers, Chinese and English and Chinese and English symbols',
      thunkTip3: 'Serial port supports outputting Wiegand signal'
    },
    showParams: {
      title: 'Display parameters',
      screenArrow: 'Screen direction',
      arrowAcross: 'Landscape',
      arrowColumn: 'Portrait',
      showText: 'Display text',
      hidden: 'Not display',
      deviceGroup: 'Device group',
      custom: 'Custom',
      scrDisplayText1Content: 'For example: Uni-Ubi Technology Co., Ltd.',
      deviceName: 'Device name',
      scrDisplayText2Content: 'For example: Device at east gate',
      showImg: 'Display image',
      previewDefaultImg: 'Check default image',
      imgStandard1: 'Photo scale is 1:1, photo size not exceeds 2M',
      imgStandard2: 'File format supports jpg, jpeg and png',
      imgStandard3: 'For example: company logo',
      imgStandard4: 'For example: QR code',
      imgStandard5: 'Used for the display when the device disabled',
      showConfig: 'Display settings',
      deviceKey: 'Device serial number',
      personCount: 'Number of people',
      disabledImg: 'Disabled interface image',
      bigScreen: 'Big-screen mode',
      normalType: 'Classic mode',
      customType: 'Custom mode',
      showForBig: 'Used for big-screen display',
      slogan: 'Slogan',
      intro: 'Introduction'
    },
    identifyType: {
      title: 'Recognition mode',
      photoIdentify: 'Face recognition',
      identifyScores: 'Face recognition threshold',
      identifyScoresTip: '(Please input integer between 0-100, the higher the score, the higher the recognition accuracy. To guarantee accuracy, the suggested value is 50-100)',
      moreIdentify: 'Multi-people recognition',
      moreIdentifyTip: 'Faces shown within recognition area will all be detected',
      singleIdentify: 'Single-person recognition',
      singleIdentifyTip: 'Only detect the biggest face within recognition area',
      cardIdentify: 'Card recognition',
      cardIdentifyTip: 'Currently, IC Card and Face&IC Card cannot coexist, as they use the same serial port output',
      recModeCardIntf: 'Card number transmission interface',
      recModeCardIntfTip: '(Restart the device to take effect after the interface type switched)',
      chunk: 'Serial port ',
      recModeCardHardware: 'External hardware type',
      hardware1: 'IC card reader',
      hardware2: 'Synjones',
      hardware3: 'Routon',
      hardware4: 'ZKT',
      hardware5: 'China Vision',
      personCard: 'Face&IC Card',
      personCardTip: 'Currently, IC Card and Face&IC Card cannot coexist, as they use the same serial port output',
      pearsonWithCard: 'Face&ID Card',
      pearsonWithCardTip: 'The same card number transmission interface cannot be used for IC Card, Face&IC Card, Face&ID Card at the same time'
    },
    dialog: {
      title: 'Device configuration failed',
      deviceName: 'Device name',
      deviceKey: 'Device serial number',
      failReason: 'Failure reasons'
    },
    message: {
      rule1: 'Please input voice broadcast custom content',
      rule2: 'Please input 1-255-bit characters',
      rule3: 'Allow {name}, {tag}, numbers, English and Chinese characters',
      rule4: 'Please input screen display text',
      rule5: 'Please input 1-255-bit characters',
      rule6: 'Please input Wiegand output custom content',
      rule7: 'Allow numbers only',
      rule8: 'Range of Wiegand 26 is 1-65535',
      rule9: 'Range of Wiegand 34 is 1-4294967295',
      rule10: 'Please input face recognition threshold',
      rule11: 'Please input integer between 1-100',
      rule12: 'Please input serial output custom content',
      rule13: 'Allow numbers, English and English symbols',
      rule14: 'Allow {phone}, {idcardNum}, {id}, numbers, English and English symbols',
      rule15: 'Please input time window',
      rule16: 'Please input relay control time',
      rule17: 'Please input integer between 100-25500',
      rule18: 'Please input the number of times that can judge the recognition failure',
      rule20: 'Please input Wiegand output custom content',
      rule21: 'Range of Wiegand 26 is 1-65535',
      rule22: 'Range of Wiegand 34 is 1-4294967295',
      rule23: 'Please input display text content 1',
      rule24: 'Please input display text content 2',
      rule27: 'File format is incorrect, please re-select',
      rule28: 'File is too large, please re-select',
      rule29: 'Please input integer between 1-20',
      rule30: 'Only allow {idcardNum}, {id} and numbers',
      rule31: 'Please input integer between 0-2147483647'
    },
    configSuccess: 'Device configured successfully!',
    configError: 'Device configuration content is error, please switch tabs and submit after verification'
  },
  // 设备列表>>检查设备: '  // Device list>>Check device',
  device_check: {
    title: 'Check the device',
    search: {
      checking: 'Checking',
      tip1: 'Check if the device is the latest version',
      tip2: 'Provide better service via version upgrade',
      tip3: 'Device searched',
      reCheck: 'Re-check',
      checkRes: 'Device searched',
      batchUpgrade: 'Batch upgrade',
      noDataTip: 'No device or client requires upgrade'
    },
    table: {
      tabs: {
        tab1: 'Same version',
        tab2: 'Device version is low',
        tab3: 'Client version is low',
        tab4: 'Offline device'
      },
      labels: {
        deviceKey: 'Device serial number',
        version: 'Software version',
        ipAddress: 'IP address',
        devicePlateName: 'Device name',
        ClientPlateName: 'Client name',
        handle: 'Operation'
      },
      sync: 'Synchronize',
      upgrade: 'Upgrade',
      enable: 'Enable',
      forceDelete: 'Force to delete',
      tip: 'Please upgrade the client version in settings'
    },
    dialog: {
      sync: 'Synchronize',
      syncDevice: 'Synchronize to device name',
      syncClient: 'Synchronize to client name'
    },
    deviceOffLine: 'Device offline',
    deviceDisabled: 'Device disabled',
    message: {
      syncSuccess: 'Synchronized successfully',
      requiredDevice: 'Please select the device to upgrade',
      hasEnable: 'Device enabled',
      forceDeleteTip: 'Force to delete the device, and will delete all device info stored in system, but keep all data in the device',
      forceDelete: 'Force to delete',
      delete: 'Delete',
      hasDelete: 'Device already deleted'
    }
  },
  // 设备列表>>添加设备>>手动添加: '  // Device list>>Add device>>Add manually',
  device_addManual: {
    title: 'Add manually',
    name: 'Name',
    ipAddress: 'IP address',
    checkDevice: 'Device detected',
    group: 'Group',
    add: 'Add',
    setPassword: 'Set device password',
    userAdminPassword: 'Use Admin password',
    setPasswordTip: 'Please set password',
    samePassword: 'Repeat the password',
    passwordLabel: 'Device password',
    hasPasswordTip: 'Device already has password, please input the password',
    message: {
      requiredName: 'Please input device name',
      requiredIpAddress: 'Please input IP address',
      requiredPassword: 'Please input password',
      requiredAgain: 'Please confirm password',
      noIp: 'No device detected in current IP address',
      requiredDevice: 'Please detect device first',
      addSuccess: 'Added successfully',
      nameLeg: 'Device name is limited to 255 characters in length'
    }
  },
  // 设备列表>>添加设备>>自动添加: '  // Device list>>Add device>>Auto add',
  device_addAuto: {
    title: 'Auto add',
    search: {
      searching: 'Searching',
      res: 'Device searched',
      reSearch: 'Check again'
    },
    tableHeader: {
      deviceKey: 'Device serial number',
      version: 'Software version',
      ipAddress: 'IP address',
      deviceName: 'Device name',
      deviceGroup: 'Device group',
      handle: 'Operation'
    },
    hasAccess: 'Accessed',
    dialog: {
      title: 'Auto add',
      labels: {
        name: 'Name',
        group: 'Group'
      },
      setPassword: 'Set device password',
      userAdminPassword: 'Use Admin password',
      requiredPassword: 'Please input password',
      requireAgain: 'Please input password again',
      hasPasswordTip: 'Device already has password'
    },
    message: {
      requiredName: 'Please input device name',
      requiredPassword: 'Please input password',
      requiredAgain: 'Please confirm password',
      addSuccess: 'Added successfully',
      nameLeg: 'Device name is limited to 255 characters in length'
    }
  },
  // 设备组>>添加设备组: '  // Device groups>>Add a device group',
  group_add: {
    editTitle: 'Edit the device group',
    addTitle: 'Add a device group',
    form: {
      name: 'Name',
      remark: 'Notes',
      device: 'Device ',
      search: 'Search',
      offLine: 'Offline',
      disabled: 'Disable'
    },
    all: 'All',
    outGroup: 'Not grouped',
    message: {
      requiredName: 'Please input the name',
      updateSuccess: 'Changed successfully',
      addSuccess: 'Added successfully'
    }
  },
  // 手动添加设备 key 值新增
  device_add_manual_confirm_self_message: 'Access control devices cannot be added to visitor verification terminal list',
  device_add_manual_confirm_self_message2: 'Whether to add this device to Access control device list?',
  device_add_manual_confirm_device_message: 'Failed to add visitor verification terminal to access control device list',
  device_add_manual_confirm_device_message2: 'Whether to add this device to visitor verification terminal list?',
  device_add_manual_confirm_button_text: 'Yes',
  device_add_manual_confirm_cancel_button_text: 'No',

  device_info_device_ip_type: 'IP type',
  device_info_device_ip_type_1: 'DHCP',
  device_info_device_ip_type_2: 'Fixed IP',
  device_info_device_has_password: 'Password',
  device_info_device_has_password_no: 'Null',
  device_info_device_has_password_exist: 'Yes',
  device_info_device_model: 'Device type',
  device_info_device_not_support: 'Not support',
  device_info_device_type1: 'Passenger analytical device',
  device_info_device_type2: 'Link',
  device_info_device_type3: '5C',
  device_info_device_type4: 'DV300 table',
  device_info_device_type5: 'DV300 module',
  device_info_device_type6: 'CV500 module',
  device_info_device_type7: '5K',
  device_info_device_type8: 'ID Verification AIO',

  // 1.2期增加文字
  ip_input_copy_error: 'Incorrect format',
  device_batch_operate_restore_text: 'Restore to default configuration',
  device_batch_operate_restore_fail: 'Device failed to restore to the default configuration',
  device_batch_operate_restore_comfirm_title: 'Restore to default configuration',
  device_batch_operate_restore_comfirm_centent: 'The device configuration will restore to the default value after restore operation',
  device_batch_operate_restore_comfirm_submit: 'Restore',
  device_batch_operate_restore_comfirm_success: 'Device restored success',
  device_config_tabs_tip: 'Please select parameters needed to be configured',
  device_config_form_recModeCardPhoto: 'Capture photo',
  device_config_form_whitelist: 'ID Card verification',
  device_config_form_whitelist_tip: 'After reading ID card information, whether it needs to be compared with the ID card number of the person in the database',
  device_upgrade_history_table_title: 'Upload history',
  device_upgrade_history_table_name: 'File name',
  device_upgrade_history_table_time: 'Upload time',
  device_upgrade_history_table_operate: 'Operation',
  device_upgrade_history_table_operate_upgrade: 'Upgrade',
  device_upgrade_history_table_operate_delete: 'Delete',
  device_upgrade_history_table_operate_delete_comfirm_title: 'Delete',
  device_upgrade_history_table_operate_delete_comfirm_content: 'It cannot be recovered after deletion',
  device_upgrade_history_table_operate_delete_comfirm_submit: 'Delete',
  device_upgrade_history_table_operate_delete_comfirm_success: 'Delete successfully',
  device_upgrade_leave_confirm_title: 'Leave',
  device_upgrade_leave_confirm_content: 'Upload will be canceled after leaving this page',
  device_upgrade_leave_confirm_submit: 'Leave',
  device_wifi_ip_conflict: 'IP address is occupied, please set another IP',
  device_add_form_lang: 'Set device language',
  device_batch_operate_lang_comfirm_title: 'Set device language',
  device_batch_operate_lang_text: 'Set device language',
  device_batch_operate_lang_fail: 'Device failed to set language',
  device_batch_operate_lang_success: 'Device set language successfully',
  device_batch_operate_lang_comfirm_form_lang_label: 'Language',
  device_batch_operate_lang_comfirm_form_submit: 'Save',
  device_batch_operate_empty_comfirm_title: 'Clear people',
  device_batch_operate_empty_comfirm_content: 'After clear, the person information will be empty in device, and all people  of the device will be revoked in authorization list of client',
  device_batch_operate_empty_text: 'Clear people',
  device_batch_operate_empty_fail: 'Device failed to clear people',
  device_batch_operate_empty_success: 'Device cleared people successfully',
  device_batch_operate_empty_comfirm_form_submit: 'Clear',
  device_config_check_ip_text: 'Verifying IP address...',

  // 体温检测
  device_batch_temperature_comfirm_title: 'Set body temperature detection',
  device_batch_operate_temperature_form_temp_check: 'Body temperature detection',
  device_batch_operate_temperature_form_temp_invalid: 'Abnormal body temperature',
  device_batch_operate_temperature_form_temp_invalid_voice: 'Voice broadcast of abnormal body temperature',
  device_batch_operate_temperature_form_temp_voice_type1: 'Broadcast abnormal body temperature and value',
  device_batch_operate_temperature_form_temp_voice_type2: 'No broadcast',
  device_batch_operate_temperature_form_temp_voice_type3: 'Custom',
  device_batch_operate_temperature_form_custom_voice_placeholder: 'Allow {temperature}, numbers, English and Chinese characters',
  device_batch_operate_temperature_form_custom_voice_example: 'e.g: {temperature} abnormal body temperature',
  device_batch_operate_temperature_form_custom_voice_validator1: 'Please input voice broadcast custom content',
  device_batch_operate_temperature_text: 'Set body temperature detection',
  device_batch_operate_temperature_fail: 'Device set body temperature detection failure',
  device_batch_operate_temperature_success: 'Set body temperature detection successfully',
  device_identify_person_temperature_number: 'Body TEMP',
  device_identify_person_temperature_state: 'TEMP state',

  device_batch_operate_device_style1: 'Tablet gate machine',
  device_batch_operate_device_style2: 'Vertical all-in-one machine',
  device_batch_operate_device_style3: 'Simple UI',
  device_batch_operate_device_style: 'Other',
  device_batch_operate_device_style_label: 'Device mode',
  device_batch_operate_device_style_tip: 'The temperature area displayed on device screen is different according to the device mode',
  device_batch_operate_device_style_placeholder: 'Please other type of device mode',

  device_batch_operate_read_temperature_type_label: 'Type of temperature measuring module',
  device_batch_operate_read_temperature_type_tip: 'It is necessary to check whether the device matches the type of temperature measuring module',
  device_batch_operate_read_temperature_type_placeholcer: 'Please input the type of temperature measuring module',
  device_batch_operate_over_lab_value_label: 'Overlap rate of temperature measuring area',
  device_batch_operate_over_lab_value_tip: 'The larger the value, the higher the matching degree between face and temperature measuring area on the screen; This parameter is not valid for device mode - tablet gate machine',
  device_batch_operate_over_lab_value_placeholder: 'Please input the overlap rate of temperature measuring area',
  // 2020-03-12
  device_batch_operate_temperature_position: 'Temperature measuring of body parts',
  device_batch_operate_temperature_position_label1: 'Forehead',
  device_batch_operate_temperature_position_label2: 'Wrist',
  device_batch_operate_temperature_position_tip: 'The prompt sound and the prompt screen of the device are different with the temperature measuring of body parts',
  device_batch_operate_temperature_pass: 'Whether pass when body temperature is abnormal',
  device_batch_operate_temperature_pass_label1: 'Not allow',
  device_batch_operate_temperature_pass_label2: 'Allow',

  device_batch_operate_temperature_measure_range: 'Effective temperature range',
  device_batch_operate_temperature_measure_range_tip: 'If the temperature is not in this range, the device will prompt to remeasure temperature',
  device_batch_operate_temperature_measure_range_label1: 'Minimum',
  device_batch_operate_temperature_measure_range_label2: 'Maximum',
  device_batch_operate_temperature_measure_validator: 'Only allow the numerical value with one decimal fraction within {min}-{max}',
  device_batch_operate_temperature_measure_placeholder1: 'Please enter the minimum effective temperature',
  device_batch_operate_temperature_measure_placeholder2: 'Please enter the maximum effective temperature',
  device_batch_operate_temperature_env_effect1: 'Low temperature compensation',
  device_batch_operate_temperature_env_effect1_tip: 'When the measuring temperature is lower than the normal body temperature due to the influence of the environment, it will be automatically compensated as the normal body temperature',
  device_batch_operate_temperature_env_effect_label1: 'Mapping source',
  device_batch_operate_temperature_env_effect_label2: 'Mapping target',

  device_batch_operate_temperature_env_effect2: 'High temperature compensation',
  device_batch_operate_temperature_env_effect2_tip: 'When turned on, the temperature detected to be in the range of the mapping source below will be adjusted to the mapping target range',
  device_batch_operate_temperature_env_effect_validator5: 'The highest value should be greater than the lowest',
  device_batch_operate_temperature_env_effect_validator6: 'The mapping source range of low temperature compensation should be smaller than that of high temperature compensation',
  device_batch_operate_temperature_env_effect_validator7: 'Please input the minimum temperature',
  device_batch_operate_temperature_env_effect_validator8: 'Please input the maximum temperature',
  device_batch_operate_temperature_env_effect: 'Environmental compensation',
  device_batch_operate_temperature_env_effect_tip: 'When turned on, it can reduce the influence of the environment on the temperature detection results',
  device_batch_operate_temperature_more_btn1: 'Fold',
  device_batch_operate_temperature_more_btn2: 'Unfold more',
  device_batch_operate_temperature_unit: 'Unit of temperature',
  device_batch_operate_temperature_unit_type1: 'Degree Celsius ℃',
  device_batch_operate_temperature_unit_type2: 'Fahrenheit ℉',
  // 设置口罩检测
  device_batch_mask_check_comfirm_title: 'Set face mask detection',
  device_batch_operate_mask_check_form_temp_check: 'Face mask detection',
  device_batch_operate_mask_check_form_temp_invalid_voice: 'Voice broadcast of no mask',
  device_batch_operate_mask_check_form_temp_voice_type1: 'Broadcast no mask',
  device_batch_operate_mask_check_form_temp_voice_type2: 'No broadcast',
  device_batch_operate_mask_check_form_temp_voice_type3: 'Custom',
  device_batch_operate_mask_check_form_custom_voice_placeholder: 'Allow numbers, English and Chinese characters',
  device_batch_operate_mask_check_form_custom_voice_example: 'e.g: No mask is not allowed to pass',
  device_batch_operate_mask_check_form_custom_voice_validator1: 'Please input voice broadcast custom content',
  device_batch_operate_mask_check_text: 'Set face mask detection',
  device_batch_operate_mask_check_fail: 'Device set face mask detection failure',
  device_batch_operate_mask_check_success: 'Set face mask detection successfully',

  // 远程开门
  device_batch_operate_remote_opendoor_text: 'Remote door-opening',
  device_batch_operate_remote_opendoor_fail: 'Device remote door-opening failure',
  device_batch_operate_remote_opendoor_success: 'Remote door-opening successfully',
  // 设备配置方案
  device_batch_operate_device_config: 'Configuration plan',
  device_batch_operate_device_config_add: 'Add configuration',
  device_batch_operate_device_config_update_time: 'Latest update time',
  device_batch_operate_device_config_default_name: 'Default Plan A',
  device_batch_operate_device_config_button1: 'Save the plan',
  device_batch_operate_device_config_button2: 'Apply to the device'
}
